{
  "name": "connected",
  "version": "0.0.2",
  "description": "Error first callback for listening on the server.",
  "main": "index.js",
  "scripts": {
    "test": "mocha $(find test -name '*.test.js')"
  },
  "repository": {
    "type": "git",
    "url": "git@github.com:3rd-Eden/connected.git"
  },
  "keywords": [
    "connected",
    "connect",
    "listen",
    "listening",
    "error",
    "online",
    "up",
    "up",
    "and",
    "away"
  ],
  "author": {
    "name": "Arnout Kazemier"
  },
  "license": "MIT",
  "devDependencies": {
    "pre-commit": "0.0.x",
    "assume": "0.0.x",
    "mocha": "1.20.x"
  },
  "readme": "# connected\n\nThis module is born out of an annoyance with the Node core. Every method that\nreceives a callback is called using an error first callback. But this is not the\ncase with servers. When you tell the server to start listening on the given port\nit can will `emit` an `error` event when it failed.\n\n## Installation\n\n```\nnpm install connected --save\n```\n\n## Usage\n\n```js\nvar connected = require('connected')\n  , http = require('http');\n\nvar app = http.createServer(function (req, res) {\n  res.end('wobble wobble');\n});\n\nconnected(app, 80, function (err) {\n  // Received an error because we are not allowed to listen on port 80\n});\n```\n\nAnd thats it.\n\n## License\n\nMIT\n",
  "readmeFilename": "README.md",
  "bugs": {
    "url": "https://github.com/3rd-Eden/connected/issues"
  },
  "homepage": "https://github.com/3rd-Eden/connected",
  "_id": "connected@0.0.2",
  "_from": "connected@>=0.0.0 <0.1.0"
}
